on:
  push:
    branches:
      - master
      - dev
jobs:
  unit_test_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zsh
        run: |
          sudo apt install zsh
      - name: Run unit tests
        run: |
          make unit_test

  unit_test_on_macOS_x86:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zsh
        run: |
          brew install zsh
      - name: Run unit tests
        run: |
          make unit_test