on:
  push:
    branches:
      - master
      - dev
jobs:
  unit_test_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zsh
        run: |
          sudo apt install zsh
      - name: Run unit tests
        run: |
          make unit_test

  unit_test_on_centos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run commands on CentOS 8
        run: |
          docker pull centos:centos8.4.2105
          docker run --rm -v $PWD:/workdir -w /workdir centos:8 bash -c "
          rm -rf /etc/yum.repos.d/*
          cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
          cat /etc/yum.repos.d/CentOS-Base.repo 
          ls -ahl /etc/yum.repos.d/*
          yum install -y make zsh
          make unit_test
          "

  unit_test_on_macOS_x86:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zsh
        run: |
          brew install zsh
      - name: Run unit tests
        run: |
          make unit_test